'use client'

import { FormEvent, ReactNode, useEffect, useState } from 'react'
import { api, getApiKey, setApiKey } from '@/lib/api'

/**
 * Every /api route requires a shared key generated by the API on first
 * boot (printed to `docker compose logs api`, and readable any time from
 * `data/api_key`). This gate asks for it once and keeps it in
 * localStorage; api.ts clears it automatically on a 401 so a revoked or
 * wrong key sends the user back here instead of silently failing.
 */
export function ApiKeyGate({ children }: { children: ReactNode }) {
  const [ready, setReady] = useState(false)
  const [needsKey, setNeedsKey] = useState(false)
  const [input, setInput] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [checking, setChecking] = useState(false)

  useEffect(() => {
    setNeedsKey(!getApiKey())
    setReady(true)
  }, [])

  async function trySubmit(e: FormEvent) {
    e.preventDefault()
    const key = input.trim()
    if (!key) return
    setChecking(true)
    setError(null)
    setApiKey(key)
    try {
      await api.health()
      setNeedsKey(false)
    } catch {
      setError('Key rejected — check the value in the API container logs or data/api_key.')
    } finally {
      setChecking(false)
    }
  }

  if (!ready) return null

  if (!needsKey) return <>{children}</>

  return (
    <div className="dash-layout" style={{ alignItems: 'center', justifyContent: 'center' }}>
      <form
        className="card"
        onSubmit={trySubmit}
        style={{ maxWidth: '28rem', width: '100%', margin: '4rem auto' }}
      >
        <h1 style={{ marginBottom: '0.5rem' }}>Observa</h1>
        <p className="muted" style={{ marginBottom: '1rem' }}>
          Paste the API key printed by the <code>api</code> service on first boot (also saved to{' '}
          <code>data/api_key</code>).
        </p>
        <div className="form">
          <label>
            API key
            <input
              type="password"
              autoFocus
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="..."
            />
          </label>
        </div>
        {error && <p className="error">{error}</p>}
        <button className="btn btn-primary" type="submit" disabled={checking}>
          {checking ? 'Checking…' : 'Unlock'}
        </button>
      </form>
    </div>
  )
}
